In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('dga_data_ready.csv')

In [156]:
dataset.tail()

isDGA     domain
159995  legit    manhunt
159996  legit     yupptv
159997  legit   bbcmundo
159998  legit  kanogames
159999  legit  roadrover

In [4]:
dataset.groupby('isDGA').count()

domain
isDGA        
dga     80000
legit   79998

In [5]:
dataset.count()

isDGA     160000
domain    159998
dtype: int64

In [17]:
#Creating a subsample of the dataset, becasue the dataset is too big to process
dataset_subset = dataset.sample(n = 50000, replace = False)


In [15]:
dataset_subset.groupby('isDGA').count()

domain
isDGA        
dga     24912
legit   25087

In [157]:
subset = dataset_subset.head(50)
subset

isDGA                            domain
40017     dga                      dwphcwtyqtoq
128952  legit                          ffffound
28080     dga                    amvbqqrdblueih
158140  legit                     superbmarking
110352  legit                           togetho
51512     dga        17yqanrqbc426tfmn1y1hchkgk
153465  legit                           cityfos
40010     dga                      ghpjdrxbmmgk
139909  legit                         bierdopje
25934     dga                          lihkxthi
128413  legit                          cuiweiju
154008  legit                   uniradioinforma
6351      dga                   oolurjtkfiwegrq
137012  legit                           jamendo
103538  legit                      pandaexpress
98671   legit                           sign-up
77183     dga        f12pm112hk2m18rs75j1ukcds4
5979      dga                          songelse
89667   legit                      companyinfoz
102124  legit            voyeurlatinocolegialas
58455     dga         reu5xq8wjj7x11s7wj0hii7zg
23762     dga                         whomcloth
5176      dga                   rtodrtwhqxdusqw
57313     dga                    ndtmoyqdbnurxq
87268   legit                          thinkfla
85450   legit                        pgwebinars
71863     dga                bipphucjvkbhhntxdp
142846  legit                        identifont
117752  legit                          interush
96061   legit                       morpakampus
27771     dga                         roomthrow
36147     dga         14yrqq7mbfm633j082b6sji17
67444     dga                    wmogmnhkfjtnpy
27909     dga        uwemqwhtchylmruovgaeyxdmsw
64285     dga                     vpfshycjdgqcd
144694  legit                             icoin
87967   legit                            cshabc
86441   legit                           amplify
79435     dga        1jlbnocu3yhtq57w0dg1q4qfoy
12618     dga                     xeldugrmbtymj
117186  legit                           klwines
108670  legit                          admarula
142631  legit                        spyropress
40045     dga  f80e2e6bf156921038c83f0b880f76c9
126686  legit                      xtremetop100
42713     dga                     jqoidjmelsvon
140353  legit                           hyipnew
109655  legit                   salemwebnetwork
151624  legit                           maiyadi
50563     dga                   aducjfaqjbkraxr

In [158]:
#splitting the word in ngrams
def splitting_in_ngrams(input_word):
    input_word=str(input_word)
    s=''
    for i in range(len(input_word)-2):
        s1 = input_word[i:i+3]
        s = s + ' ' + s1 
    s = s[1:]
    return(s)

In [11]:
#creating a corpus of documents. A document is the list of ngrams extracted from a domain
corpus =[]
for i in range(len(dataset_subset)):
    temp = dataset_subset.iloc[i][1]
    temp = str(temp)
    temp = temp.lower()
    temp = splitting_in_ngrams(temp)
    corpus.append(temp)
print(corpus)

['lly lye yen eno nox oxt xtu tub ubt btd tdg', '05a 5a9 a9b 9b8 b85 858 58b 8b3 b35 35f 5fb fb1 b13 13c 3c7 c7c 7c7 c78 78c 8c1 c1d 1da da8 a81 811 116 16b 6b8 b8e 8e0', 'ari riv ive veh ehe hea ear', 'hel ell llo lot otr tra rad ade', 'cin inc nco cod odi dia ias', 'kis isa sah ahe hem ema mas asp spu put uti tih', 'mat ath tho hov ove ver erf rfl flo low', 'roy oyx yxb xbu bux uxg xgw gwl wln lnb nbc bct', 'mee eet etc tcr cru run unc nch', 'vqc qce ces eso soj ojo job obd bdq dqm qmv mvj', 'r0n 0ns nsu suj ujj jjy jy6 y6k 6kl kl2 l21 21v 1v4 v41 415 15q 5qo qo1 o1j 1jf jfa fa5 a53 53g', 'med edi dia ia- a-r -ri ric ich', 'sha hag ag6 g6d 6d1 d10 10w 0wb wb7 b7l 7lg lg1 g17 176 76d 6dp dpx pxl xla lat atp tpj pj2 j2v', '13u 3uh uhb hbh bhx hx1 x1n 1nn nn3 n32 32c 2cj cj2 j2z 2zh zh3 h37 37g 7g1 g1m 1m7 m7p 7pp ppg pgf', 'wer er- r-w -we wei eis iss ss- s-w -wa was', 'ylm lmu mud udl dld', 'tgp gpk pkn kni niv ivz vzl zld ldl dlh lhd hdy dyx yxc xcx cxw xwe weq', 'itr tr2 r20 201 010

In [22]:
# Creating the Bag of Words model on a smaller vocabulary to understand how it works
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 3)
cv.fit_transform(['bam amw mwa wap apl plo lof off ffx lon', 'lon ong ngw gwi win']).toarray()

for item in cv.fit_transform(['bam amw mwa wap apl plo lof off ffx lon', 'lon ong ngw gwi win']).toarray():
    print(item)
    
print(cv.transform(['bam amw']).toarray())

[1 1 1]
[0 0 1]
[[1 0 0]]


In [159]:
X_array = subset.iloc[:,1].values
X_array


array(['dwphcwtyqtoq', 'ffffound', 'amvbqqrdblueih', 'superbmarking',
       'togetho', '17yqanrqbc426tfmn1y1hchkgk', 'cityfos', 'ghpjdrxbmmgk',
       'bierdopje', 'lihkxthi', 'cuiweiju', 'uniradioinforma',
       'oolurjtkfiwegrq', 'jamendo', 'pandaexpress', 'sign-up',
       'f12pm112hk2m18rs75j1ukcds4', 'songelse', 'companyinfoz',
       'voyeurlatinocolegialas', 'reu5xq8wjj7x11s7wj0hii7zg', 'whomcloth',
       'rtodrtwhqxdusqw', 'ndtmoyqdbnurxq', 'thinkfla', 'pgwebinars',
       'bipphucjvkbhhntxdp', 'identifont', 'interush', 'morpakampus',
       'roomthrow', '14yrqq7mbfm633j082b6sji17', 'wmogmnhkfjtnpy',
       'uwemqwhtchylmruovgaeyxdmsw', 'vpfshycjdgqcd', 'icoin', 'cshabc',
       'amplify', '1jlbnocu3yhtq57w0dg1q4qfoy', 'xeldugrmbtymj',
       'klwines', 'admarula', 'spyropress',
       'f80e2e6bf156921038c83f0b880f76c9', 'xtremetop100',
       'jqoidjmelsvon', 'hyipnew', 'salemwebnetwork', 'maiyadi',
       'aducjfaqjbkraxr'], dtype=object)

In [160]:
#Splitting the dataset into grams
X_gram =[]
for i in range(len(subset)):
    temp = subset.iloc[i][1]
    temp = str(temp)
    temp = temp.lower()
    temp = splitting_in_ngrams(temp)
    X_gram.append(temp)


In [162]:
#Transforming the dataset into a CountVector
X_vector = cv.fit_transform(X_gram).toarray()
X_vector

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [163]:
#Label encoding y
y = subset.iloc[:,0].values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0])

In [164]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_vector, y, test_size = 0.20, random_state = 0)


In [165]:
X_train

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int64)

In [166]:
y_train

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [167]:
X_test

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [168]:
y_test

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 1])

In [169]:
# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
LG_classifier = LogisticRegression(random_state = 0)
classifier = LG_classifier.fit(X_train, y_train)


In [170]:
#saving the Logistic Regression model parameters
import json
classification_model_param = {}
classification_model_param['coef'] = list(classifier.coef_)
classification_model_param['intercept'] = list(classifier.intercept_)

coeff = list(classifier.coef_)
intercept = list(classifier.intercept_)
print(coeff)
print(intercept)

[array([-0.41678261, -0.02692822,  0.6500398 ])]
[0.08077043957659603]


In [151]:
#predicting y_test using coeff and intercept. Trying to understand how these parameters are used in the LG_classifier
import numpy as np
from sklearn.utils.extmath import safe_sparse_dot

print(coeff)
print(intercept)
print(X_test)

out = np.matmul(X_test,coeff[0])

out_1 = safe_sparse_dot(X_test,coeff[0]) + intercept
print(out_1)

[array([-0.41678261, -0.02692822,  0.6500398 ])]
[0.08077043957659603]
[[0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[ 0.08077044  0.08077044 -0.33601217  0.08077044  0.08077044  0.08077044
  0.08077044  0.08077044  0.08077044  0.08077044]


In [171]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)


[1 1 0 1 1 1 1 1 1 1]
[1 1 1 1 0 1 0 0 0 1]


In [125]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 4]
 [1 5]]


0.5